### ISSUE TITLE
Fargate

### ISSUE THREAD

**Issue by jocca1985** [fdfk/ecsServiceRestart#2]
This doesn't work with fargate instances. Getting 'botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the UpdateService operation: Task definition does not support launch_type FARGATE.'

**Comment by oranmoshai** [comment]
Thanks for the feedback can you test the new version with the fargate support?

**Comment by jocca1985** [comment]
Thanks for the fix.
1) Fargate worked now but for some reason draining the previous task definition takes more than 5 minutes. Maybe it's up to my configuration so need to check.
2) EC2 is not working now cause memory and cpu are not mandatory. So when sending empty string I get 'botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RegisterTaskDefinition operation: Invalid 'cpu' setting for task.'

**Comment by oranmoshai** [comment]
Thanks tested in my environment works now
