### ISSUE TITLE
Not working for fargate and cannot set latest version taskDefinitionArn

### ISSUE THREAD

**Issue by Eddie-he** [fdfk/ecsServiceRestart#5]
![20180901180042](https://user-images.githubusercontent.com/3214491/44944915-d53caa80-ae11-11e8-9e9e-2620c285fd21.png)

**Comment by oranmoshai** [comment]
@Eddie-he Thanks for opening the issue.
ECS have new option force new deployment instead clone the task definition and redeploy. 
Can you test this branch ? https://github.com/oranmoshai/ecsServiceRestart/tree/force-new-deployment
